// FAKE DATA
export const games = [
  {
    id: 1,
    title: "Grand Theft Auto V - PlayStation 4",
    url: "https://m.media-amazon.com/images/I/61+s8HfeFoL._SX342_.jpg",
    originalPrice: 29.99,
    salePrice: 11.99,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Metroid Dread - Nintendo Switch",
    url: "https://m.media-amazon.com/images/I/71E+KjuboFL._SL1500_.jpg",
    originalPrice: 59.99,
    salePrice: 39.99,
    rating: 4.5,
  },
  {
    id: 3,
    title: "Halo Master Chief Collection - Xbox One",
    url: "https://s3.gaming-cdn.com/images/products/734/orig/halo-the-master-chief-collection-xbox-one-cover.jpg",
    originalPrice: 29.99,
    salePrice: 12.99,
    rating: 4,
  },
  {
    id: 4,
    title: "NBA 2K22 - PlayStation 5",
    url: "https://media.gamestop.com/i/gamestop/11151959/NBA-2K22----PlayStation-5",
    originalPrice: 59.99,
    salePrice: 24.99,
    rating: 1.5,
  },
  {
    id: 5,
    title: "Kingdom Hearts 2.5 HD Remix - PlayStation 3",
    url: "https://upload.wikimedia.org/wikipedia/en/thumb/1/19/KH_HD_2.5_ReMIX_NA_Boxart.jpg/220px-KH_HD_2.5_ReMIX_NA_Boxart.jpg",
    originalPrice: 19.99,
    salePrice: 9.99,
    rating: 4,
  },
  {
    id: 6,
    title: "Super Mario Galaxy 2 - Nintendo Wii",
    url: "https://m.media-amazon.com/images/I/81iCVhLDJFL._SY445_.jpg",
    originalPrice: 19.99,
    salePrice: 9.99,
    rating: 5,
  },
  {
    id: 7,
    title: "The Elder Scrolls V: Skyrim - Xbox 360",
    url: "https://m.media-amazon.com/images/I/91nOykIoY3L._SY445_.jpg",
    originalPrice: 14.99,
    salePrice: 9.99,
    rating: 4.5,
  },
  {
    id: 8,
    title: "Donkey Kong Country Returns 3D - Nintendo 3DS",
    url: "https://m.media-amazon.com/images/I/81RYG5cWuML._SL1500_.jpg",
    originalPrice: 14.99,
    salePrice: 11.99,
    rating: 4,
  },
  {
    id: 9,
    title: "Ratchet & Clank - PlayStation 2",
    url: "https://upload.wikimedia.org/wikipedia/en/b/b6/RaCbox.jpg",
    originalPrice: 14.99,
    salePrice: 9.99,
    rating: 4,
  },
  {
    id: 10,
    title: "Mega Man 3 - Nintendo NES",
    url: "https://upload.wikimedia.org/wikipedia/en/4/49/Megaman3_box.jpg",
    originalPrice: 59.99,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 11,
    title: "Sonic & Knuckles - Sega Genesis",
    url: "https://m.media-amazon.com/images/I/51JV6YK81FL.jpg",
    originalPrice: 12.99,
    salePrice: 9.99,
    rating: 4.5,
  },
  {
    id: 12,
    title: "Marvel vs. Capcom 2 - Sega Dreamcast",
    url: "https://i.pinimg.com/236x/10/91/97/1091976640c5f42ed50f41d45ddeb5f9--sega-dreamcast-childhood-games.jpg",
    originalPrice: 89.99,
    salePrice: null,
    rating: 4.5,
  },
  {
    id: 13,
    title: "Guilty Gear Strive - PlayStation 5",
    url: "https://m.media-amazon.com/images/I/81mcWVTH2xS._SX342_.jpg",
    originalPrice: 59.99,
    salePrice: 19.99,
    rating: 4.5,
  },
  {
    id: 14,
    title: "Rocket League - Xbox One",
    url: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6290/6290418_sd.jpg",
    originalPrice: 29.99,
    salePrice: 9.99,
    rating: 4.5,
  },
  {
    id: 15,
    title: "Far Cry 6 - Xbox Series X",
    url: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6421/6421541_sd.jpg",
    originalPrice: 49.99,
    salePrice: null,
    rating: 4,
  },
  {
    id: 16,
    title: "Puyo Puyo Tetris 2 - Nintendo Switch",
    url: "https://m.media-amazon.com/images/I/81Jc4vFX9tL._SL1500_.jpg",
    originalPrice: 39.99,
    salePrice: 19.99,
    rating: 3.5,
  },
  {
    id: 17,
    title: "Final Fantasy IV The Complete Collection - Sony PSP",
    url: "https://upload.wikimedia.org/wikipedia/en/4/4a/FFIV_Complete_Collection.jpg",
    originalPrice: 19.99,
    salePrice: 9.99,
    rating: 4.5,
  },
  {
    id: 18,
    title: "Pokemon Sun - Nintendo 3DS",
    url: "https://m.media-amazon.com/images/I/81mWKPCNRPL._SX425_.jpg",
    originalPrice: 29.99,
    salePrice: 19.99,
    rating: 3.5,
  },
  {
    id: 19,
    title: "Kirby Super Star Ultra - Nintendo DS",
    url: "https://m.media-amazon.com/images/I/61OuurypHFL.jpg",
    originalPrice: 29.99,
    salePrice: 14.99,
    rating: 4.5,
  },
  {
    id: 20,
    title: "Contra 4 - Nintendo DS",
    url: "https://m.media-amazon.com/images/I/51bPJ+4mBCL.jpg",
    originalPrice: 29.99,
    salePrice: 12.99,
    rating: 4.5,
  },
  {
    id: 21,
    title: "Bomber Man 64 - Nintendo 64",
    url: "https://www.mobygames.com/images/covers/l/17734-bomberman-64-nintendo-64-front-cover.jpg",
    originalPrice: 29.99,
    salePrice: 14.99,
    rating: 4,
  },
  {
    id: 22,
    title: "Turtles in Time - Nintendo SNES",
    url: "https://upload.wikimedia.org/wikipedia/en/4/4e/Turtles_in_Time_%28SNES_cover%29.jpg",
    originalPrice: 79.99,
    salePrice: 49.99,
    rating: 4.5,
  },
  {
    id: 23,
    title: "Metal Gear Solid - PlayStation",
    url: "https://upload.wikimedia.org/wikipedia/en/3/33/Metal_Gear_Solid_cover_art.png",
    originalPrice: 29.99,
    salePrice: 14.99,
    rating: 5,
  },
  {
    id: 24,
    title: "Super R-Type - Nintendo SNES",
    url: "https://upload.wikimedia.org/wikipedia/en/b/b3/SuperrtypeSNES_boxart.JPG",
    originalPrice: 19.99,
    salePrice: 9.99,
    rating: 3,
  },
];